server:
  port:  ${PORT:8867}
message:  Configuracion de Categoria en el servidor levantado;
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    password:  123456789
    url:  jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto:  update
      database-platform:  org.hibernate.dialect.MySQLDialect
    cloud:
      config:
        url: http://localhost:8860
