server:
  port:  9090
message:  Configuracion del Customer en el servidor levantado;

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/customer
    username:  postgres
    password:  123456789
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql:  true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    register-with-eureka:  true
    #fetch-registry:  false
    serviceurl:
      defaultZone: http://localhost:8850/eureka/
message: Configuracion de Customer en el servidor levantado!
